from collections.abc import Callable
from typing import Protocol


class DockWidgetContract(Protocol):
    def add_user_message(self, text: str) -> int: ...

    def add_system_message(self, text: str) -> int: ...

    def add_result_message(self, text: str) -> int: ...

    def add_tool_message(self, text: str) -> int: ...

    def add_rejected_message(self, text: str) -> int: ...

    def mark_tool_done(self, message_id: int, ok: bool = True) -> None: ...

    def add_plan_message(self, plan_lines: list[str]) -> int: ...

    def confirm_destructive(self, lines: list[str]) -> bool: ...

    def mark_plan_completed(self, message_id: int) -> None: ...

    def mark_plan_cancelled(self, message_id: int) -> None: ...

    def set_busy(self, busy: bool) -> None: ...

    def clear_prompt(self) -> None: ...

    def replay(self, messages: list[dict[str, str]]) -> None: ...

    def set_session_source(self, provider: Callable[[], list[tuple[str, str]]]) -> None: ...
