from collections.abc import Callable
from typing import Any, Protocol


class DockWidgetContract(Protocol):
    def add_user_message(self, text: str) -> int: ...

    def mark_rewind_point(self, entry_id: int, message: int) -> None: ...

    def choose_rewind(self, project_available: bool) -> str | None: ...

    def add_system_message(self, text: str) -> int: ...

    def add_result_message(self, text: str) -> int: ...

    def add_visual(self, spec: dict[str, Any]) -> int: ...

    def add_question(self, question: str, options: list[str]) -> int: ...

    def add_tool_message(self, text: str) -> int: ...

    def add_stream_chunk(self, text: str) -> None: ...

    def add_thinking_chunk(self, text: str) -> None: ...

    def finish_stream(self, markdown: str) -> bool: ...

    def add_rejected_message(self, text: str) -> int: ...

    def mark_tool_done(self, message_id: int, ok: bool = True, note: str = "") -> None: ...

    def add_plan_message(self, plan_lines: list[str], applies_itself: bool = False) -> int: ...

    def confirm_data_sharing(self, endpoint: str) -> bool: ...
    def confirm_destructive(self, lines: list[str], details: str = "") -> bool: ...

    def mark_plan_completed(self, message_id: int, undoable: bool = False) -> None: ...

    def mark_plan_failed(self, message_id: int, undoable: bool = False) -> None: ...

    def mark_plan_undone(self, message_id: int) -> None: ...

    def mark_plan_step(self, message_id: int, index: int, state: str, note: str = "") -> None: ...

    def set_project_line(self, text: str) -> None: ...

    def set_model(self, name: str) -> None: ...

    def show_outcome(self, kind: str) -> None: ...

    def set_conversation_title(self, title: str) -> None: ...

    def note_conversation_saved(self) -> None: ...

    def set_active_layer(self, name: str, detail: str = "") -> None: ...

    def context_mention(self) -> str: ...

    def mark_plan_cancelled(self, message_id: int) -> None: ...

    def set_busy(self, busy: bool) -> None: ...

    def set_context(self, used: int, window: int, spent: int, requests: int = 0) -> None: ...

    def set_configured(self, configured: bool) -> None: ...

    def clear_prompt(self) -> None: ...

    def replay(self, messages: list[dict[str, Any]]) -> None: ...

    def set_session_source(self, provider: Callable[[], list[tuple[str, str, float, bool]]]) -> None: ...

    def set_skill_source(self, provider: Callable[[], list[tuple[str, str, str]]]) -> None: ...

    def set_layer_source(self, provider: Callable[[], list[tuple[str, str, str]]]) -> None: ...

    def focus_prompt(self) -> None: ...

    def restore_prompt(self, text: str) -> None: ...

    def keep_stream(self) -> str: ...

    def mention_layers(self, names: list[str]) -> None: ...

    def add_attachment(self, path: str) -> None: ...

    def take_attachments(self) -> list[str]: ...

    def set_work_mode(self, mode: str) -> None: ...

    def offer_plan(self) -> None: ...
